import './globals.css'
import { Cabin } from 'next/font/google'
import 'animate.css';

const cabin = Cabin({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cabin.className} animate__animated animate__fadeIn text-white/80 selection:bg-primary-800 selection:text-white/80`}>
        {children}</body>
    </html>
  )
}
