import './globals.css'
import { Cabin } from 'next/font/google'

const cabin = Cabin({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        {children}</body>
    </html>
  )
}
