import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.scss'
import { Button, Text, Element, Heading, Row, Portion, InputField, TextArea, HRule } from "fictoan-react"

import React from 'react';
import { useState, useEffect } from 'react';







export default function Home() {

  const router = useRouter()


  return (     
    
    <div className={styles.container}>
      <Head>
        <title>Listen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/headphones.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet" />
      </Head>


      {/* HERO SECTION */}
      <Row marginBottom='none' marginTop='small'>
        {/* DESKTOP MARK UP */}
        <Portion desktopSpan="one-third" hideOnTabPT hideOnMobile>
          <Element
            as="img"
            src="/headphones.png"
            marginBottom="small"
            // style={{ width: "164px" }}
            style={{ width: "192px", marginRight: "auto" }}
          />
        </Portion>

        {/* NON DESKTOP MARK UP */}
        <Portion marginBottom='small' showOnlyOnTabPT showOnlyOnMobile>
          <Element
            as="img"
            src="/headphones.png"
            marginBottom="small"
            // style={{ width: "164px" }}
            style={{ width: "192px", margin: "auto" }}
          />
        </Portion>

        {/* DESKTOP MARK UP */}
        <Portion desktopSpan="two-third" hideOnTabPT hideOnMobile>
          <Heading as="h4" weight='500' marginBottom='nano'>Spending too much time on screen?</Heading>
          <Heading as="h2" weight='300' marginBottom='micro'><strike>Read</strike> Listen!</Heading>
          <Button kind="primary" size="medium" marginBottom='none' marginRight='nano'
            onClick={() => {router.push('/app')}}
          >START LISTENING</Button>
          {/* <Button kind="secondary" size="medium" marginBottom='none'
            onClick={() => {router.push('/app#help')}}
          >HELP </Button> */}
          <Text marginBottom='none'>Google Chrome recommended</Text>        
        </Portion>

        {/* NON DESKTOP MARK UP */}
        <Portion showOnlyOnTabPT showOnlyOnMobile>
          <Heading align='center' as="h4" weight='500' marginBottom='nano'>Spending too much time on screen?</Heading>
          <Heading align='center' as="h2" weight='300' marginBottom='small'><strike>Read</strike> Listen!</Heading>
          <div className='horizontally-center-this'>
            <Button kind="primary" size="medium" marginBottom='none' marginRight='nano'
              onClick={() => {router.push('/app')}}
            >START LISTENING</Button>
            <Button kind="secondary" size="medium" marginBottom='none'
              onClick={() => {router.push('/app#help')}}
            >INSTALL APP</Button>
          </div>
          <Text marginBottom='none'>Google Chrome recommended</Text>
        </Portion>
      </Row>



      <HRule kind='primary' marginTop='medium' marginBottom='medium' sideMargin='medium' style={{color : `${styles.primaryColor}`}}/>



      {/* FEATURES */}
      <Row marginBottom='small'>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          {/* https://stackoverflow.com/questions/34521797/how-to-add-multiple-classes-to-a-reactjs-component */}
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>cloud_download</span></Text>
          <Text align='center'>Fetch from links</Text>
        </Portion>
        <Portion desktopSpan='1' hideOnMobile hideOnTabLS hideOnTabPT></Portion>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>description</span></Text>
          <Text align='center'>Paste text</Text>
        </Portion>
        <Portion desktopSpan='1' hideOnMobile hideOnTabLS hideOnTabPT></Portion>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>devices</span></Text>
          <Text align='center'>All your devices</Text>
        </Portion>
        <Portion desktopSpan='1' hideOnMobile hideOnTabLS hideOnTabPT></Portion>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>translate</span></Text>
          <Text align='center'>Languages</Text>
        </Portion>
      </Row>



      {/* <HRule kind='primary' marginTop='medium' marginBottom='medium' sideMargin='medium' style={{color : `${styles.primaryColor}`}} id='app'/> */}

      <Text align='center' marginBottom='none'>Another project by <a href='https://yakshag.github.io' target="blank">Vivek</a></Text>
      <Text align='center' marginBottom='small'>Icon attribution: Music vector created by rawpixel.com - www.freepik.com</Text>
    </div>
  )


























      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div> */}
}
