import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.scss'
import { Button, Text, Element, Heading, Row, Portion, InputField, TextArea, HRule } from "fictoan-react"

import React from 'react';
import Select from 'react-select';

import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';

import { useState } from 'react';



const EnglishOptions = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' },
];

const NonEnglishOptions = [
  { value: 'ABC', label: 'ABC' },
  { value: 'KN', label: 'KN' },
  { value: 'TN', label: 'TN' },
];

const groupedOptions = [
  {
    label : 'English voices',
    options : EnglishOptions,
  },
  {
    label : 'Non English voices',
    options : NonEnglishOptions,
  }
];


// For dropdown styling
const customStyles = {
  option: (provided, state) => ({
    ...provided,
    color: 'white'
  }),
}




export default function Home() {
  const router = useRouter()
  const [value, setValue] = useState("Potato potato tomato potato.");
  
  return (
    // <div className={styles.container}>
     
    
    <div className={styles.container}>
      <Head>
        <title>Listen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/headphones.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet" />
      </Head>


      {/* HERO SECTION */}
      <Row marginBottom='none' marginTop='small'>
        {/* DESKTOP MARK UP */}
        <Portion desktopSpan="one-third" hideOnTabPT hideOnMobile>
          <Element
            as="img"
            src="/headphones.png"
            marginBottom="small"
            // style={{ width: "164px" }}
            style={{ width: "192px", marginRight: "auto" }}
          />
        </Portion>

        {/* NON DESKTOP MARK UP */}
        <Portion marginBottom='small' showOnlyOnTabPT showOnlyOnMobile>
          <Element
            as="img"
            src="/headphones.png"
            marginBottom="small"
            // style={{ width: "164px" }}
            style={{ width: "192px", margin: "auto" }}
          />
        </Portion>

        {/* DESKTOP MARK UP */}
        <Portion desktopSpan="two-third" hideOnTabPT hideOnMobile>
          <Heading as="h4" weight='500' marginBottom='nano'>Spending too much time on screen?</Heading>
          <Heading as="h2" weight='300' marginBottom='small'><strike>Read</strike> Listen!</Heading>
          <Button kind="primary" size="medium" marginBottom='none' marginRight='nano'
            onClick={() => {router.push('/#app')}}
          >START LISTENING</Button>
          <Button kind="secondary" size="medium" marginBottom='none'
            onClick={() => {router.push('/#help')}}
          >HELP </Button>
        <Text marginBottom='none'>Another project by <a href='https://yakshag.github.io' target="blank">Vivek</a></Text>
        </Portion>

        {/* NON DESKTOP MARK UP */}
        <Portion showOnlyOnTabPT showOnlyOnMobile>
          <Heading align='center' as="h4" weight='500' marginBottom='nano'>Spending too much time on screen?</Heading>
          <Heading align='center' as="h2" weight='300' marginBottom='small'><strike>Read</strike> Listen!</Heading>
          <div className='horizontally-center-this'>
            <Button kind="primary" size="medium" marginBottom='none' marginRight='nano'
              onClick={() => {router.push('/#app')}}
            >START LISTENING</Button>
            <Button kind="secondary" size="medium" marginBottom='none'
              onClick={() => {router.push('/#help')}}
            >INSTALL APP</Button>
          </div>
        <Text align='center' marginBottom='none'>Another project by <a href='https://yakshag.github.io' target="blank">Vivek</a></Text>
        </Portion>
      </Row>



      <HRule kind='primary' marginTop='medium' marginBottom='medium' sideMargin='medium' style={{color : `${styles.primaryColor}`}}/>



      {/* FEATURES */}
      <Row marginBottom='small'>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          {/* https://stackoverflow.com/questions/34521797/how-to-add-multiple-classes-to-a-reactjs-component */}
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>cloud_download</span></Text>
          <Text align='center'>Fetch from links</Text>
        </Portion>
        <Portion desktopSpan='1' hideOnMobile hideOnTabLS hideOnTabPT></Portion>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>description</span></Text>
          <Text align='center'>Paste text</Text>
        </Portion>
        <Portion desktopSpan='1' hideOnMobile hideOnTabLS hideOnTabPT></Portion>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>devices</span></Text>
          <Text align='center'>All your devices</Text>
        </Portion>
        <Portion desktopSpan='1' hideOnMobile hideOnTabLS hideOnTabPT></Portion>
        <Portion padding='nano' desktopSpan='5' mobileSpan='12' tabLSSpan='12' tabPTSpan='12'>
          <Text align='center'><span className={`material-icons ${styles.icon48}`}>translate</span></Text>
          <Text align='center'>Languages</Text>
        </Portion>
      </Row>



      <HRule kind='primary' marginTop='medium' marginBottom='medium' sideMargin='medium' style={{color : `${styles.primaryColor}`}} id='app'/>



      {/* APP */}
      <Heading as="h4" marginBottom='micro'>What will you listen to, today?</Heading>
      <Row marginBottom='small' gutters='none' className={styles.surface}>
        {/* LEFT PORTION */}
        <Portion padding='micro' desktopSpan="15">
          <InputField
            label="Paste link to article"
            placeholder="https://yourfavblog.com/article-12"
            errorText="Looks invalid. Check?"
            type="url"
          />

          <Row marginBottom='none'>
            <Portion desktopSpan='6' mobileSpan='8' tabLSSpan='8' tabPTSpan='8'>
              <Button kind="secondary" size="small" marginBottom='micro'>FETCH</Button>
            </Portion>
            <Portion desktopSpan='18' mobileSpan='16' tabLSSpan='16' tabPTSpan='16'>
              <Text margin='none'>— OR —</Text>
            </Portion>
          </Row>
          
          <TextArea
            label="Paste article text"
            placeholder="A word, a pragraph or a long article"
            rows={10}
            style={{color : `${styles.textColor}`}}
          />
          
        </Portion>

        
        {/* RIGHT PORTION */}
        <Portion desktopSpan='9' padding='micro'>
          <Text marginTop='none' className={styles.primaryFontColor} marginBottom='nano'>Pick a voice</Text>

          {/* https://react-select.com/styles */}
          {/* https://yarnpkg.com/package/react-select */}
          <Select
            styles={customStyles}
            options={groupedOptions}
            // placeholder='That matches the text'
            theme={(theme) => ({
              ...theme,
              colors: {
                ...theme.colors,
                primary: "#03DAC599",
                primary25: "#03DAC53D",
                primary50: "#2E2E2E",
                neutral0: "#2E2E2E",
                neutral80: "white",
              }
            })}
          />
          <Button kind="secondary" size="small" marginTop='nano' marginRight='nano'>RELOAD VOICES</Button>
          <Button kind="secondary" size="small" marginTop='nano'
            onClick={() => {router.push('/#help')}}
          >HELP</Button>

          {/* RESET STATE */}
          <Element as='div' >
            <Heading as='h6' weight='300' marginTop='small'>Tips for picking voices</Heading>
            <Text>👉 Pick a voice that matches the language of your text.</Text>
            <Text showOnlyOnDesktop>👉 On desktops, use Google Chrome for best voices.</Text>
            <Text showOnlyOnMobile showOnlyOnTabLS showOnlyOnTabPT>👉 On mobile devices, voices are provided by the device text to speech engine.</Text>
          </Element>

          {/* SPEAKING STATE */}
          <Element as='div' hidden>
            <Element as='div' marginTop='small' style={{ display: 'flex', alignItems: 'center' }}>
              <Heading as='h6' weight='300' marginRight='micro' >Reading now</Heading>
              <Element as='img' src='/speaking.gif' className={styles.icon48} style={{ width: '36px', alignSelf: 'center' }} />
            </Element>
            <Text id='readingText'><i>You are listening to this text.</i></Text>
          </Element>
        </Portion>

        {/* PLAYER STRIP */}
        <Portion desktopSpan='24' marginTop='nano'>
          <div className={styles.playerStrip}>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
              <div>
                <Button kind='custom' bgColor='transparent' size='tiny'><Text align='center'><span className={`material-icons ${styles.icon48}`}>skip_previous</span></Text></Button>
              </div>
              <div>
                <Button kind='custom' bgColor='transparent' size='tiny'><Text align='center'><span className={`material-icons ${styles.icon96}`}>play_arrow</span></Text></Button>
              </div>
              <div hidden>
              <Button kind='custom' bgColor='transparent' size='tiny'><Text align='center'><span className={`material-icons ${styles.icon96}`}>pause</span></Text></Button>
            </div>
              <div>
                <Button kind='custom' bgColor='transparent' size='tiny'><Text align='center'><span className={`material-icons ${styles.icon48}`}>skip_next</span></Text></Button>
              </div>
            </div>
            <div style={{position : 'absolute', width: '100%', top : '65%'}}>
            <Button kind='custom' bgColor='transparent' size='medium' isFullWidth><Text align='center' weight='700' className={styles.primaryFontColor}>STOP</Text></Button>
              </div>
          </div>
        </Portion>
      </Row>


      <HRule kind='primary' marginTop='medium' marginBottom='medium' sideMargin='medium' style={{color : `${styles.primaryColor}`}} id='help'/>



      {/* HELP */}
      <Element as='div' marginBottom='huge'>
        <Heading as="h4" marginBottom='micro'>Need help?</Heading>    
      <Tabs>
        <TabList style={{color: `${styles.primaryColor}`}}>
          <Tab>Install app</Tab>
          <Tab>Voices</Tab>
          <Tab>Fetch / paste</Tab>
        </TabList>

        <TabPanel>
          <Text weight='700' size="large" marginBottom='none'>Mobile devices</Text>
          <Text marginTop='none' marginBottom='none'><strong>Android:</strong> Browser three dots menu > Add to Home screen</Text>
          <Text marginTop='none'><strong>iOS:</strong> Share button > Add to Home screen</Text>

          <Text weight='700' size="large" marginBottom='none'>Desktop</Text>
          <Text marginTop='none'>You can simply bookmark this page for regular use.</Text>
        </TabPanel>
        <TabPanel>
        <Text>👉 Pick a voice that matches the text language.</Text>
          <Text>👉 On desktops, use Google Chrome for best voices.</Text>
          <Text>👉 On mobile devices, voices provided by the default text to speech engine are used.</Text>
          <Text weight='700' size="large" marginBottom='none'>I do not see any voices in the list</Text>
          <Text marginTop='none'>Refresh the page a couple of times or try a different browser such as Google Chrome. If none of the browsers help, then your device does not support text to speech.</Text>

          <Text weight='700' size="large" marginBottom='none'>I do not see any voices in the list</Text>
          <Text marginTop='none'>Refresh the page a couple of times or try a different browser such as Google Chrome. If none of the browsers help, then your device does not support text to speech.</Text>
        </TabPanel>
        <TabPanel>
          <Text weight='700' size="large" marginBottom='none'>I do not see any voices in the list</Text>
          <Text marginTop='none'>Please refresh the page a couple of times. If you still do not see any voices in the list, please try a different browser such as Google Chrome. If none of the browsers help, then your device does not support text to speech.</Text>
        </TabPanel>
      </Tabs>
      </Element>
      
    </div>
  )


























      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div> */}
}
